export const ContactTypes = {
    GET_CONTACT: 'GET_CONTACT',
    ADD_CONTACT: 'ADD_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT',
    GET_CONTACT_BY_ID: 'GET_CONTACT_BY_ID',
    EDIT_CONTACT_BY_ID: 'EDIT_CONTACT_BY_ID',
    ERROR_DELETE: 'ERROR_DELETE',
    ERROR_POST: 'ERROR_POST'
}